name: Publish Package

# Add these lines to tell GitHub when to run
on:
  release:
    types: [created] # Runs when you create a new Release
  workflow_dispatch:   # Allows you to run it manually from the "Actions" tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sanmugamks'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
